const asset = (path) => '../CATALOGO_BAMIRA/' + path;
const catalogo = [
  ['massagem','Kit Massagem Relaxante','kits',49.99,'Kit de autocuidado com vela corporal, chá e escalda-pés para um ritual de pausa.','MASSAGEM/WhatsApp Image 2026-07-06 at 15.07.42.jpeg|MASSAGEM/kit_completo_original_preservado_02.png|MASSAGEM/kit_completo_original_preservado_01.jpg|MASSAGEM/Captura de tela 2026-07-22 180445.png|MASSAGEM/Captura de tela 2026-07-22 180415.png'],
  ['verbena','Vela Aromática Verbena','outros',24.9,'Vela verde em copo de vidro, com presença fresca e leve para iluminar a rotina.','VERBENA/100ml/vela_verbena_100ml_2.jpeg|VERBENA/100ml/vela_verbena_100ml_1.jpg'],
  ['oceano-erva-doce','Vela Oceano e Erva-Doce','outros',45.9,'Copo azul translúcido com conchas e pedrinhas, inspirado na calmaria do mar.','OCEANO - ERVA DOCE/oceano_erva_doce3.jpeg|OCEANO - ERVA DOCE/oceano_erva_doce2.jpeg|OCEANO - ERVA DOCE/oceano_erva_doce1.jpeg'],
  ['kit-morango','Kit Morangos (2 unds)','kits',14.9,'Conjunto com 2 velas em formato de morango, vibrante e feito para presentear.','KIT_MORANGO/slide_tela_principal_morango.png|KIT_MORANGO/carrossel_morango_2.png|KIT_MORANGO/carrossel_morango_1.png'],
  ['kit-morango-4','Kit Morangos (4 unds)','kits',24.9,'Conjunto com 4 velas em formato de morango, vibrante e feito para presentear.','KIT_MORANGO/slide_tela_principal_morango.png|KIT_MORANGO/carrossel_morango_2.png|KIT_MORANGO/carrossel_morango_1.png'],
  ['trio-mini','Kit Trio Mini','kits',70,'Trio de velas delicadas com formas de cacto, flor e coração em embalagem presenteável.','VELAS TRIO MINI/kit_vela_duo_fora_da_caixa_cacto_coracao_site.jpeg|VELAS TRIO MINI/coracao_dourado_site.png|VELAS TRIO MINI/feed_flor_vermelha_pedra_site.png|VELAS TRIO MINI/kit_velas_cacto_coracao_dourado_flor_site.png|VELAS TRIO MINI/kit_vela_trio_dentro_da_caixa_cacto_flor_coracao_site.jpeg|VELAS TRIO MINI/post_cacto_vidro_site.png|VELAS TRIO MINI/velas_cacto_e_coracao_site.png'],
  ['kit-ameixa-corpo-flutuante','Kit Ameixa Negra e Corpo Flutuante','kits',65,'Kit com as velas Ameixa Negra e Corpo Flutuante, em uma combinação especial.','AMEIXA NEGRA - COPO FLUTUANTE/kit_velas_ameixanegra_corpo_flutuante.jpeg|AMEIXA NEGRA - COPO FLUTUANTE/kit_ameixanegra_corpo_flutuante2.jpeg'],
  ['gourmet-maracuja','Vela Gourmet Flor de Maracujá','gourmet',39.9,'Vela cremosa em copo de vidro, decorada como uma sobremesa tropical e luminosa.','GOUTMET_MARACUJA/gourmet_maracuja_slide_pagina_principal_site.png|GOUTMET_MARACUJA/gourmet_maracuja_01_site.png'],
  ['mini-velas','Mini Vela Floral','outros',8.9,'Mini velas aromáticas em copo, com flores em cera e cores marcantes.','MINI VELAS/WhatsApp Image 2026-06-17 at 16.56.09.jpeg|MINI VELAS/WhatsApp Image 2026-05-13 at 11.01.37.jpeg|MINI VELAS/WhatsApp Image 2026-05-13 at 11.01.36.jpeg|MINI VELAS/vela_rosa.jpeg|MINI VELAS/vela_flor_maracuja_tres.jpeg|MINI VELAS/vela_flor_maracuja.JPEG|MINI VELAS/vela_canela_tres.jpeg|MINI VELAS/vela_canela.jpeg|MINI VELAS/velas_kit.jpeg|MINI VELAS/IMG_3219.JPEG'],
  ['suculenta-cacto','Vela Suculenta e Cacto','outros',24.9,'Velas esculturais em vasinhos, inspiradas em um pequeno jardim desértico.','SUCULENTA E CACTO/WhatsApp Image 2026-04-26 at 22.09.07.jpeg|SUCULENTA E CACTO/WhatsApp Image 2026-04-26 at 22.09.07 (1).jpeg|SUCULENTA E CACTO/suculenta_e_cacto1.png|SUCULENTA E CACTO/suculenta1.png|SUCULENTA E CACTO/cacto1.png'],
  ['gourmet-cafe','Vela Gourmet Café','gourmet',20,'Vela em xícara com grãos decorativos, criada para lembrar uma pausa de café recém-passado.','GOUTMET_CAFÉ/vela_cafe_mesa.png|GOUTMET_CAFÉ/vela_cafe_graos.jpeg|GOUTMET_CAFÉ/vela_cafe_close_graos.png'],
  ['concha-algodao','Vela Concha Algodão','outros',39.9,'Vela azul com concha e flores em cera, combinando leveza, textura e fantasia marinha.','CONCHA  - ALGODAO/concha_algodao2.jpeg|CONCHA  - ALGODAO/concha_algodao1.jpeg'],
  ['ameixa-negra','Vela Ameixa Negra','outros',29.9,'Vela aromática Ameixa Negra, com acabamento artesanal e aroma marcante.','AMEIXA NEGRA - COPO FLUTUANTE/vela_ameixa_negra1.jpeg|AMEIXA NEGRA - COPO FLUTUANTE/vela_ameixa_negra2.jpeg|AMEIXA NEGRA - COPO FLUTUANTE/vela_ameixa_negra_3.jpeg'],
  ['corpo-flutuante','Vela Corpo Flutuante','outros',65,'Vela aromática Corpo Flutuante, com acabamento artesanal e presença delicada.','AMEIXA NEGRA - COPO FLUTUANTE/vela_corpo_flutuante1.jpeg|AMEIXA NEGRA - COPO FLUTUANTE/vela_corpo_flutuante2.jpeg'],
  ['gourmet-canela','Vela Gourmet Canela','gourmet',55,'Vela aromática de canela com acabamento artesanal e proposta acolhedora.','GOURMET_CANELA/vela_prosperidade_transparente02_site.png|GOURMET_CANELA/vela_prosperidade_transparente01_site.png']
].map(([id,nome,categoria,preco,descricao,imagens]) => ({ id, nome, categoria, preco, descricao, imagens: imagens.split('|').map(asset) }));

const heroSlides = [
  ['trio-mini','Um presente cheio de detalhes','Conheça o kit de velas em formas delicadas.','VELAS TRIO MINI/kit_vela_duo_fora_da_caixa_cacto_coracao_site.jpeg'],
  ['kit-ameixa-corpo-flutuante','Uma combinação especial','Ameixa Negra e Corpo Flutuante em um kit presenteável.','AMEIXA NEGRA - COPO FLUTUANTE/kit_velas_ameixanegra_corpo_flutuante.jpeg'],
  ['kit-morango','Um presente cheio de encanto','O Kit Morango une cor, perfume e afeto em cada detalhe.','KIT_MORANGO/carrossel_morango_2.png']
];
const cart = typeof Cart !== 'undefined' ? new Cart() : null;
const grid = document.querySelector('#products-grid'), result = document.querySelector('#catalog-result');
const formatPrice = (value) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
let filter = 'todos', heroIndex = 0, heroTimer, closeTimer;

function createCard(product) {
  const card = document.createElement('article'); let imageIndex = 0;
  const hasVolume = product.categoria !== 'kits';
  const volumeSelector = hasVolume ? '<div class="volume-selector" role="group" aria-label="Volume da vela"><button type="button" class="volume-option" data-volume="100ml" aria-pressed="true">100 ml</button><button type="button" class="volume-option" data-volume="50ml" aria-pressed="false">50 ml</button></div>' : '';
  card.className = 'product-card'; card.dataset.id = product.id; card.dataset.nome = product.nome; card.dataset.preco = product.preco; card.dataset.precoBase = product.preco; card.dataset.imagem = product.imagens[0];
  if (hasVolume) card.dataset.volume = '100ml';
  const hasGallery = product.imagens.length > 1;
  card.innerHTML = `<div class="product-image-container"><img class="product-image" loading="lazy" decoding="async">${hasGallery ? '<button type="button" class="image-control image-previous" aria-label="Foto anterior"><i class="fas fa-chevron-left"></i></button><button type="button" class="image-control image-next" aria-label="Próxima foto"><i class="fas fa-chevron-right"></i></button><span class="image-count" aria-live="polite"></span>' : ''}</div><div class="product-info"><h3 class="product-title"></h3><p class="product-description"></p><p class="product-price"></p>${volumeSelector}<div class="quantity-selector"><button type="button" class="quantity-button quantity-decrease" aria-label="Diminuir quantidade">-</button><input type="number" class="quantity-display" value="1" min="1" max="99" aria-label="Quantidade"><button type="button" class="quantity-button quantity-increase" aria-label="Aumentar quantidade">+</button></div><button type="button" class="add-to-cart-button"><i class="fas fa-shopping-cart"></i> Adicionar ao Carrinho</button></div>`;
  const image = card.querySelector('.product-image');
  const showImage = (index) => { imageIndex = (index + product.imagens.length) % product.imagens.length; image.src = encodeURI(product.imagens[imageIndex]); image.alt = `${product.nome} — foto ${imageIndex + 1}`; const count = card.querySelector('.image-count'); if (count) count.textContent = `${imageIndex + 1} / ${product.imagens.length}`; };
  showImage(0); card.querySelector('.product-title').textContent = product.nome; card.querySelector('.product-description').textContent = product.descricao; card.querySelector('.product-price').textContent = formatPrice(product.preco);
  if (hasGallery) { card.querySelector('.image-previous').onclick = () => showImage(imageIndex - 1); card.querySelector('.image-next').onclick = () => showImage(imageIndex + 1); }
  return card;
}
function bindCards() { document.querySelectorAll('.product-card').forEach((card) => { const input = card.querySelector('.quantity-display'); const quantity = () => Math.max(1, Math.min(99, Number.parseInt(input.value, 10) || 1)); card.querySelectorAll('.volume-option').forEach((button) => button.onclick = () => { const volume = button.dataset.volume; const price = volume === '50ml' ? Number(card.dataset.precoBase) / 2 : Number(card.dataset.precoBase); card.dataset.volume = volume; card.dataset.preco = price; card.querySelector('.product-price').textContent = formatPrice(price); card.querySelectorAll('.volume-option').forEach((option) => option.setAttribute('aria-pressed', String(option === button))); }); card.querySelector('.quantity-decrease').onclick = () => input.value = Math.max(1, quantity() - 1); card.querySelector('.quantity-increase').onclick = () => input.value = Math.min(99, quantity() + 1); input.onchange = () => input.value = quantity(); card.querySelector('.add-to-cart-button').onclick = (event) => { const button = event.currentTarget; const hasVolume = Boolean(card.dataset.volume); cart.addItem({ id: hasVolume ? `${card.dataset.id}-${card.dataset.volume}` : card.dataset.id, nome: hasVolume ? `${card.dataset.nome} (${card.dataset.volume})` : card.dataset.nome, preco: Number(card.dataset.preco), imagem: card.dataset.imagem, quantidade: quantity() }); refreshCart(); const original = button.innerHTML; button.classList.add('added'); button.innerHTML = '<i class="fas fa-check"></i> Adicionado'; setTimeout(() => { button.classList.remove('added'); button.innerHTML = original; }, 1200); input.value = 1; }; }); }
function renderProducts() { const list = filter === 'todos' ? catalogo : catalogo.filter((product) => product.categoria === filter); grid.replaceChildren(...list.map(createCard)); const categoryNames = { gourmet: 'Gourmet', kits: 'Kits' }; result.textContent = filter === 'todos' ? `${list.length} produtos disponíveis` : `${list.length} produtos em ${categoryNames[filter]}`; bindCards(); }
function setFilter(next, scroll) { filter = next; document.querySelectorAll('.catalog-filter').forEach((button) => button.classList.toggle('is-active', button.dataset.filter === next)); renderProducts(); if (scroll) document.querySelector('#catalogo').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function openProductDialog(productId) { const product = catalogo.find((item) => item.id === productId); if (!product) return; const dialog = document.querySelector('#product-dialog'); const image = dialog.querySelector('.product-dialog-image'); const priceLabel = dialog.querySelector('.product-dialog-price'); const volumeSelector = dialog.querySelector('.product-dialog-info .volume-selector'); let selectedVolume = '100ml'; image.src = encodeURI(product.imagens[0]); image.alt = product.nome; dialog.querySelector('#product-dialog-title').textContent = product.nome; dialog.querySelector('.product-dialog-description').textContent = product.descricao; volumeSelector.hidden = product.categoria === 'kits'; const updateVolume = (volume) => { selectedVolume = volume; const price = volume === '50ml' ? product.preco / 2 : product.preco; priceLabel.textContent = formatPrice(price); volumeSelector.querySelectorAll('.volume-option').forEach((button) => button.setAttribute('aria-pressed', String(button.dataset.volume === volume))); }; if (volumeSelector.hidden) priceLabel.textContent = formatPrice(product.preco); else { volumeSelector.querySelectorAll('.volume-option').forEach((button) => button.onclick = () => updateVolume(button.dataset.volume)); updateVolume(selectedVolume); } dialog.querySelector('.product-dialog-add').onclick = () => { if (!cart) return; const hasVolume = product.categoria !== 'kits'; const price = hasVolume && selectedVolume === '50ml' ? product.preco / 2 : product.preco; cart.addItem({ id: hasVolume ? `${product.id}-${selectedVolume}` : product.id, nome: hasVolume ? `${product.nome} (${selectedVolume})` : product.nome, preco: price, imagem: product.imagens[0], quantidade: 1 }); refreshCart(); dialog.close(); }; dialog.showModal(); }
function renderHero() { const slides = document.querySelector('#hero-slides'), dots = document.querySelector('#hero-dots'); heroSlides.forEach(([id,title,text,image], index) => { const slide = document.createElement('article'); slide.className = 'hero-slide'; slide.innerHTML = `<img src="${encodeURI(asset(image))}" alt="${title}"><div class="hero-overlay"><p class="hero-eyebrow">Bamira artesanal</p><h2>${title}</h2><p class="hero-text">${text}</p><button type="button" class="hero-cta" aria-haspopup="dialog">Ver produto <i class="fas fa-arrow-right"></i></button></div>`; slide.querySelector('.hero-cta').onclick = () => openProductDialog(id); slides.append(slide); const dot = document.createElement('button'); dot.className = 'hero-dot'; dot.type = 'button'; dot.setAttribute('aria-label', `Ir para slide ${index + 1}`); dot.onclick = () => showHero(index); dots.append(dot); }); showHero(0); }
function showHero(index) { heroIndex = (index + heroSlides.length) % heroSlides.length; document.querySelectorAll('.hero-slide').forEach((slide, i) => slide.classList.toggle('is-active', i === heroIndex)); document.querySelectorAll('.hero-dot').forEach((dot, i) => { dot.classList.toggle('is-active', i === heroIndex); dot.setAttribute('aria-current', i === heroIndex ? 'true' : 'false'); }); clearInterval(heroTimer); heroTimer = setInterval(() => showHero(heroIndex + 1), 5500); }
function refreshCart() { if (!cart) return; const items = cart.getItems(), badge = document.querySelector('.cart-badge'), list = document.querySelector('#cart-items'), empty = document.querySelector('.cart-empty-message'), checkout = document.querySelector('#checkout-button'); badge.textContent = cart.getTotalQuantity(); list.replaceChildren(); empty.classList.toggle('hidden', items.length > 0); checkout.disabled = !items.length; items.forEach((item) => { const row = document.createElement('div'); row.className = 'cart-item'; row.innerHTML = '<div class="cart-item-details"><strong></strong><span class="unit-price"></span><span class="subtotal"></span></div><div class="cart-item-actions"><div class="cart-quantity-controls"><button type="button" class="cart-decrease">-</button><span></span><button type="button" class="cart-increase">+</button></div><button type="button" class="cart-remove">Remover</button></div>'; row.querySelector('strong').textContent = item.nome; row.querySelector('.unit-price').textContent = `Preço unitário: ${formatPrice(item.preco)}`; row.querySelector('.subtotal').textContent = `Subtotal: ${formatPrice(item.preco * item.quantidade)}`; row.querySelector('.cart-quantity-controls span').textContent = item.quantidade; row.querySelector('.cart-decrease').onclick = () => { cart.updateQuantity(item.id, item.quantidade - 1); refreshCart(); }; row.querySelector('.cart-increase').onclick = () => { cart.updateQuantity(item.id, item.quantidade + 1); refreshCart(); }; row.querySelector('.cart-remove').onclick = () => { cart.removeItem(item.id); refreshCart(); }; list.append(row); }); document.querySelector('#cart-total').textContent = formatPrice(cart.getTotalPrice()); }
function openCart() { clearTimeout(closeTimer); document.querySelector('#cart-panel').classList.remove('hidden'); document.querySelector('#cart-backdrop').classList.remove('hidden'); requestAnimationFrame(() => { document.querySelector('#cart-panel').classList.add('open'); document.querySelector('#cart-backdrop').classList.add('visible'); }); }
function closeCart() { document.querySelector('#cart-panel').classList.remove('open'); document.querySelector('#cart-backdrop').classList.remove('visible'); closeTimer = setTimeout(() => { document.querySelector('#cart-panel').classList.add('hidden'); document.querySelector('#cart-backdrop').classList.add('hidden'); }, 250); }
document.querySelectorAll('.catalog-filter').forEach((button) => button.onclick = () => setFilter(button.dataset.filter, true)); document.querySelector('.hero-control-previous').onclick = () => showHero(heroIndex - 1); document.querySelector('.hero-control-next').onclick = () => showHero(heroIndex + 1); document.querySelector('#product-dialog').onclick = (event) => { if (event.target === event.currentTarget) event.currentTarget.close(); }; renderHero(); renderProducts(); refreshCart(); document.querySelector('.cart-link').onclick = (event) => { event.preventDefault(); document.querySelector('#cart-panel').classList.contains('open') ? closeCart() : openCart(); }; document.querySelector('.cart-close').onclick = closeCart; document.querySelector('#cart-backdrop').onclick = closeCart; document.querySelector('#checkout-button').onclick = () => { if (cart.getTotalQuantity()) window.location.href = 'checkout.html'; };
